theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
A-s = ":w"
A-x = ":bc"

[keys.insert]
# f = { d = ":nomal_mode"}
# "A-q" = "normal_mode"
j = { k = "normal_mode" }
